In [2]:
import numpy as np
import pandas as pd

In [3]:
x=np.array([1,2,3,4])
print(x)
x=np.random.rand(1000000)
print(x)
w=np.random.rand(1000000)
print(w)
y = np.random.randint(2, size=1000000)
print(y)


[1 2 3 4]
[0.05352351 0.66158852 0.77446256 ... 0.68854602 0.72177118 0.70375342]
[0.0971727  0.59136557 0.37940631 ... 0.95337451 0.29655092 0.23343409]
[0 1 0 ... 0 1 1]


In [4]:
import time
tic= time.time()
z=np.dot(w,x)
toc=time.time()
print("vectorization using numpy : ",str(1000*(toc-tic)),"ms")
print(z)


vectorization using numpy :  0.0 ms
249923.17987380392


In [5]:
tic=time.time()
c=0
for i in range(1000000):
    c+=x[i]*w[i]
toc=time.time()
print("non vectorization :",str(1000*(toc-tic)),"ms")
print(z)



non vectorization : 614.0456199645996 ms
249923.17987380392


# Logistic regression derivatives

In [6]:
def gradient_descent(w, x, b, y, p):
    for i in range(1000):
        m=x.size
        z = np.dot(w.T, x) + b
        a = 1 / (1 + np.exp(-z))
        j = -1/m * np.sum(y * np.log(a) + (1 - y) * np.log(1 - a))
        dz = a - y
        dw = 1/m * np.dot(x, dz.T)
        db = 1/m * np.sum(dz)
        w -= p * dw
        b -= p * db
        print(j, dw, db)

In [18]:

gradient_descent(w,x,1,y,0.5)


C:\Users\lolug\AppData\Local\Temp\ipykernel_15612\96678385.py:5: RuntimeWarning: overflow encountered in exp
  a = 1 / (1 + np.exp(-z))
C:\Users\lolug\AppData\Local\Temp\ipykernel_15612\96678385.py:6: RuntimeWarning: divide by zero encountered in log
  j = -1/m * np.sum(y * np.log(a) + (1 - y) * np.log(1 - a))
C:\Users\lolug\AppData\Local\Temp\ipykernel_15612\96678385.py:6: RuntimeWarning: invalid value encountered in multiply
  j = -1/m * np.sum(y * np.log(a) + (1 - y) * np.log(1 - a))


nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574947 -0.49962399999999996
nan 0.24995288652409617 0.5003759999999999
nan -0.24967782496574

# Broadcasting


In [10]:
A=np.array([[1,2,3,4],
            [3,4,5,6],
            [9,9,8,7]])

cal = A.sum(axis=0)
print(cal)
percent=100*A/cal #broadcasting
print(percent)

[13 15 16 17]
[[ 7.69230769 13.33333333 18.75       23.52941176]
 [23.07692308 26.66666667 31.25       35.29411765]
 [69.23076923 60.         50.         41.17647059]]
